DEVICE_PATH := device/sts/a04br3
VENDOR_PATH := vendor/sts/a04br3
BOARD_VENDOR := sts
BOARD_DEVICE := a04br3
ALLOW_MISSING_DEPENDENCIES := true
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml
#BOARD_CHARGER_SHOW_PERCENTAGE := true

#カメラを無効
USE_CAMERA_STUB := false
CAMERA_DAEMON_NOT_PRESENT := true
BOARD_HAS_CAMERA := false

# test
#BOARD_CONNECTIVITY_VENDOR := MediaTek
BOARD_CONNECTIVITY_MODULE := MT6630

#wifi..てすと…。
BOARD_HAVE_WIFI := true
TARGET_WLAN_CHIP := mt6630
WLAN_CHIPSET := $(TARGET_WLAN_CHIP)
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WLAN_DEVICE := MediaTek
BOARD_WIFI_VENDOR := MediaTek
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_DRIVER_FW_PATH_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_FW_PATH_STA := /system/vendor/firmware/WIFI_RAM_CODE_MT6630
WIFI_DRIVER_FW_PATH_AP := /system/vendor/firmware/WIFI_RAM_CODE_MT6630
WIFI_DRIVER_FW_PATH_P2P := /system/vendor/firmware/WIFI_RAM_CODE_MT6630
WIFI_DRIVER_STATE_CTRL_PARAM := "/dev/wmtWifi"
WIFI_DRIVER_STATE_ON := 1
WIFI_DRIVER_STATE_OFF := 0


#artエラーの為追加
WITH_DEXPREOPT := true
#DISABLE_DEXPREOPT := true
#DONT_DEXPREOPT_PREBUILTS := true
#DEX_PREOPT_DEFAULT := nostripping
USE_DEX2OAT_DEBUG := false
#PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := --compiler-filter=verify
#PRODUCT_DEX_PREOPT_BOOT_FLAGS := --compiler-filter=verify

#PRODUCT_DEX_PREOPT_BOOT_FLAGS := --compiler-filter=verify-profile
#PRODUCT_DEX_PREOPT_DEFAULT_FLAGS := --compiler-filter=speed-profile

#PRODUCT_DEXPREOPT_SPEED_APPS := \
    Syste

# disable
TARGET_NO_TELEPHONY := true
BOARD_GPS_LIBRARIES := false
BOARD_HAS_GPS := false
BOARD_HAVE_RADIO := false
TARGET_NO_RADIO:= false
BOARD_HAS_NFC := false
BOARD_HAS_HDMI := false
BOARD_SUPPORTS_SOUND_TRIGGER := false

# key
TARGET_PROVIDES_KEYMASTER := false
#BOARD_USE_SOFT_GATEKEEPER := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_2ND_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_SMP := true
TARGET_IS_64_BIT := true
TARGET_BUILD_64BIT := true
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_USES_64_BIT_BINDER := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_BUILD_VARIANT := userdebug
TARGET_CPU_CORTEX_A53 := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_MEMCPY_OPT_DISABLE := true

#oat
DEX2OAT_TARGET_ARCH := arm64
DEX2OAT_TARGET_CPU_VARIANT := cortex-a53
DEX2OAT_TARGET_CPU_VARIANT_RUNTIME := default
DEX2OAT_TARGET_INSTRUCTION_SET_FEATURES := default
DEX2OAT_IMAGE_XMS := 64m
DEX2OAT_IMAGE_XMX := 128m
DEX2OAT_XMS := 64m
DEX2OAT_XMX := 256m

#ota
TARGET_OTA_ASSERT_DEVICE := TAB-A04-BR3,a04br3
AB_OTA_UPDATER := false
#BLOCK_BASED_OTA := true

#test
BOARD_SUPPRESS_SECURE_ERASE := true
DISABLE_ASHMEM_TRACKING := true
BOARD_NO_SECURE_DISCARD := true
TARGET_NO_SENSOR_PERMISSION_CHECK := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/BOOT/BOOT/boot/boot_mode
BACKLIGHT_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
BOARD_RED_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/red"
BOARD_GREEN_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/green"
BOARD_BLUE_LED_PATH := "/sys/devices/platform/leds-mt65xx/leds/blue"

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a04br3
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Display
DEVICE_RESOLUTION := 1280x800
TARGET_PROVIDES_LIBLIGHT := true

# Graphics
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/egl.cfg
USE_OPENGL_RENDERER := true
TARGET_USES_C2D_COMPOSITION := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
#TARGET_USES_OVERLAY := true
#TARGET_USES_ION := true
#TARGET_DISPLAY_USE_RETIRE_FENCE := true
EXTENDED_FONT_FOOTPRINT := true

BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HWC_SUPPORT := true
MTK_HWC_VERSION := 1.4.0
MTK_GPU_VERSION := rgx clark 1.7ED
OVERRIDE_RS_DRIVER := libRSDriver.so

# Bluetooth
#MTK_BT_SUPPORT := yes
#BOARD_HAVE_BLUETOOTH := true
#BOARD_HAVE_BLUETOOTH_MTK := true
#BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true

# audio
USE_XML_AUDIO_POLICY_CONF := 1
BOARD_USES_MTK_AUDIO := true
TARGET_OMX_LEGACY_RESCALING := true

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true

# Kernel
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x03f88000
BOARD_KERNEL_TAGS_OFFSET := 0x0df88000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
TARGET_KERNEL_CONFIG := a04br3_defconfig
TARGET_KERNEL_SOURCE := kernel/sts/a04br3

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
endif

# Vendor partition configure
BOARD_USES_VENDORIMAGE := false
# Platformm
TARGET_SOC := mt8167
TARGET_BOARD_PLATFORM := mt8167
TARGET_BOARD_PLATFORM_GPU := PowerVR Rogue GE8300
BOARD_AVB_ENABLE := false

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/recovery/fstab.mt8167
RECOVERY_SDCARD_ON_DATA := true
LZMA_RAMDISK_TARGETS := recovery

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Hack: prevent anti rollback
#PLATFORM_SECURITY_PATCH := 2099-12-31
#PLATFORM_VERSION := 16.1.0

# Properties
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true


# Soong
PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)
include vendor/sts/a04br3/BoardConfigVendor.mk
# SELinux
#BOARD_SEPOLICY_DIRS := \
	#$(DEVICE_PATH)/sepolicy/
BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp_policy
SELINUX_IGNORE_NEVERALLOWS := true
